// INHABITANTS
export const INHABITANTS_FETCH = 'INHABITANTS_FETCH';
export const INHABITANTS_LOAD_DATA = 'INHABITANTS_LOAD_DATA';
export const INHABITANTS_DISPLAY_ITEMS = 'INHABITANTS_DISPLAY_ITEMS';
export const INHABITANTS_ONE_MORE_PAGE = 'INHABITANTS_ONE_MORE_PAGE';

// FILTERS
export const FILTERS_CREATE = 'FILTERS_CREATE';
export const FILTERS_UPDATE = 'FILTERS_UPDATE';
export const FILTERS_SEARCH = 'FILTERS_SEARCH';
export const FILTERS_SET_AGE = 'FILTERS_SET_AGE';
export const FILTERS_SET_WEIGHT = 'FILTERS_SET_WEIGHT';
export const FILTERS_SET_HEIGHT = 'FILTERS_SET_HEIGHT';
export const FILTERS_SET_PROFESSION = 'FILTERS_SET_PROFESSION';
export const FILTERS_SET_HAIR = 'FILTERS_SET_HAIR';
